openapi: 3.0.3
info:
  title: Case backend - loan simulations
  description: |-
    This is a Loan Simulation Server based on the OpenAPI 3.0 specification.
  version: 1.0.11
servers:
  - url: http://localhost:8080
tags:
  - name: Loan Simulation
    description: Fast loan simulations
paths:
  /loan/simulation:
    post:
      tags:
        - Loan Simulation
      summary: Perform a personalized loan simulation for a client.
      description: |
        This endpoint receives the client and loan data and returns the monthly installment amount,
        the total payment amount, and the total interest paid.
      operationId: processLoanSimulation
      requestBody:
        $ref: '#/components/requestBodies/LoanSimulationRequest'
      responses:
        '200':
          description: Loan simulation completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanSimulationResponse'
        '400':
          description: Invalid or missing request data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanSimulationErrorResponse'
        '500':
          description: Error processing the loan simulation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error processing the loan simulation."
components:
  schemas:
    LoanSimulationData:
      type: object
      properties:
        loanAmount:
          type: number
          format: double
          example: 10000.00
        clientBirthDate:
          type: string
          example: "20/10/1999"
        paymentTermMonths:
          type: integer
          format: int32
          example: 10
      required:
        - loanAmount
        - clientBirthDate
        - paymentTermMonths
    LoanSimulationResponse:
      description: Loan simulation result
      type: object
      properties:
        totalPaymentAmount:
          type: string
          example: "R$ 12.950,46"
        monthlyInstallmentAmount:
          type: string
          example: "R$ 1.295,05"
        totalInterestPaid:
          type: string
          example: "R$ 2.950,46"
    LoanSimulationErrorResponse:
      properties:
        error:
          type: string
          example: "The provided parameters are invalid or missing required data."

  requestBodies:
    LoanSimulationRequest:
      description: Data required for loan simulation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoanSimulationData'

    LoanSimulationRequestArray:
      description: List of loan simulation object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/LoanSimulationData'
